export const cardPairs = [
  { id: 1, left: "Melhor frio", right: "Melhor quente" },
  { id: 2, left: "Fraco", right: "Forte" },
  { id: 3, left: "Cheira mal", right: "Cheira bem" },
  { id: 4, left: "Superpoder útil", right: "Superpoder inútil" },
  { id: 5, left: "Lanche", right: "Refeição" },
  { id: 6, left: "Filme bom", right: "Filme ruim" },
  { id: 7, left: "Fácil de matar", right: "Difícil de matar" },
  { id: 8, left: "Parte do corpo útil", right: "Parte do corpo inútil" },
  { id: 9, left: "Invenção útil", right: "Invenção inútil" },
  { id: 10, left: "Perdoável", right: "Imperdoável" },
  { id: 11, left: "Música boa", right: "Música ruim" },
  { id: 12, left: "Grifinória", right: "Sonserina" },
  { id: 13, left: "Inofensivo", right: "Nocivo" },
  { id: 14, left: "Para crianças", right: "Para adultos" },
  { id: 15, left: "Vilão", right: "Héroi" },
  { id: 16, left: "Lugar barulhento", right: "Lugar silencioso" },
  { id: 17, left: "Pessoa boa", right: "Pessoa ruim" },
  { id: 18, left: "Duro", right: "Suave" },
  { id: 19, left: "Requer sorte", right: "Requer habilidade" },
  { id: 20, left: "Sem sabor", right: "Saboroso" },
  { id: 21, left: "Fácil de usar", right: "Difícil de usar" },
  { id: 22, left: "Não essencial", right: "Essencial" },
  { id: 23, left: "Desconhecido", right: "Famoso" },
  { id: 24, left: "Baixas calorias", right: "Calórico" },
  { id: 25, left: "Barato", right: "Caro" },
  { id: 26, left: "O livro era melhor", right: "O filme era melhor" },
  {
    id: 27,
    left: "Bicho de estimação comum",
    right: "Bicho de estimação exótico",
  },
  { id: 28, left: "Sem talento", right: "Talentoso" },
  { id: 29, left: "Pessoa que você bate", right: "Pessoa que você apanha" },
  { id: 30, left: "Fruta", right: "Vegetal" },
  { id: 31, left: "Pequeno", right: "Grande" },
  { id: 32, left: "Talento", right: "Habilidade" },
  { id: 33, left: "Pokémon forte", right: "Pokémon fraco" },
  { id: 34, left: "Nome de cachorro", right: "Nome de gato" },
  { id: 35, left: "Melhor de dia", right: "Melhor de noite" },
  { id: 35, left: "Trabalho chato", right: "Trabalho divertido" },
  { id: 36, left: "Time pequeno", right: "Time grande" },
  { id: 37, left: "Comida de botequim", right: "Comida de restaurante chique" },
  { id: 38, left: "Jogo antigo", right: "Jogo atual" },
  { id: 39, left: "Opinião impopular", right: "Consenso geral" },
];
